### ISSUE TITLE
Bug: Search Bar Functionality To Filter Out Projects based on names

### ISSUE THREAD

**Issue by sagnik2001** [varunKT001/tomper-wear-ecommerce#11]
### Describe the Bug

To add the search bar functionality to filter out products. In the sidebar, of the filter category, the search bar should allow users to search for products when there is a large number of products to avoid the tedious task of scrolling for their product.

### Steps to reproduce the behavior

On navigating to "/products" there is a search bar at the sidebar which at present moment doesn't give any search results.

### Expected behavior
On searching any value that matches the product's name it will filter out the data and display the results, thus saving a lot of time. 

![Screenshot from 2022-03-02 19-19-46](https://user-images.githubusercontent.com/74464019/156374169-519615c8-a12d-4aaf-b623-9e050e09cc0b.png)

Now its not showing any result, I would like to work on it and make it work

Kindly assign this issue to me, under GSsoC22

**Comment by varunKT001** [comment]
Hey @sagnik2001 👋,
I have checked it, it's working if you type all lower case. But still, it's not the expected behavior. There is one more problem, when we type, it only matches the product names starting with the typed string. 

You have to fix these two things:
- Filter products irrespective of case.
- Filter products if the search string is a substring of the product's name. 

I'm assigning this issue to you 🚀

**Comment by sagnik2001** [comment]
Okay
