### ISSUE TITLE
Feature Request: Adding issue forms for the repo

### ISSUE THREAD

**Issue by MonarchGitHub** [varunKT001/tomper-wear-ecommerce#15]
I want to add a few issue forms so that it will be convenient for new contributors to open issues. There are already issue templates for this project but they are deprecated now, issue forms instead work way better. I plan to create  **Bug Report** and **Feature Request** forms. 

**_The Bug Report issue form will have the following fields_**

- **Description of the bug**
- **How to Reproduce**
- **Expected behavior**
- **Urgency indicator**
- **Desktop Info (OS, Version, Browser, etc):**

**_The Feature Request issue form will have the following fields_**

- **Is your feature request related to a problem? Please describe.**
- **Describe the solution you'd like**
- **Describe alternatives you've considered**

**Comment by varunKT001** [comment]
Hey @MonarchGitHub 👋,
It's a great idea, I was also thinking of making some issue forms as they will be more convenient 😅.
Now since you are here, you can go ahead 🚀

One suggestion:
- In the Feature request issue form, instead of `Describe alternatives you've considered` create `Additional context (if any)`.
Just like it is in the current Feature request issue template.
- Similarly, for the Bug report issue form, add an `Additional context (if any)`.

Also just make sure to thoroughly check the forms on some demo repository 👍

**Comment by MonarchGitHub** [comment]
Yeah, that sounds great, I'll start right away.
