### ISSUE TITLE
Bug: Spelling mistake

### ISSUE THREAD

**Issue by codercool3r** [varunKT001/tomper-wear-ecommerce#2]
**In the about page of the website, in the last line, it is given 'react' instead of 'reach'**

**I would like to modify it*

**'reach'**

![Screenshot from 2022-03-01 09-14-28](https://user-images.githubusercontent.com/91977735/156101884-8ce313b6-606a-4a60-8cf3-8a7ddf3f11e1.png)

**I would like to solve this issue under GSSOC'22 @varunKT001 **

**Comment by varunKT001** [comment]
Sharp eyes @codercool3r 👍 
Since this project was added, at last, mentors' allotment and other stuff are still pending. Also, I'm yet to create the contribution guidelines and a setup guide.
Don't worry, I'll assign this issue to you, once things are on track 👍 

PS: From next on, while creating an issue or pull request, make sure to strictly follow the provided templates. You can leave things blank which are not applicable, but just follow the pattern.

**Comment by codercool3r** [comment]
> Sharp eyes @codercool3r +1 Since this project was added, at last, mentors' allotment and other stuff are still pending. Also, I'm yet to create the contribution guidelines and a setup guide. Don't worry, I'll assign this issue to you, once things are on track +1
> 
> PS: From next on, while creating an issue or pull request, make sure to strictly follow the provided templates. You can leave things blank which are not applicable, but just follow the pattern.

Sure, I will make sure I follow the template
Thank you

**Comment by varunKT001** [comment]
Hey @codercool3r 👋,
Mentors allotment will take some time 😅
I'm assigning you the issue and you can work upon it 👍

**Comment by codercool3r** [comment]
> Hey @codercool3r wave, Mentors allotment will take some time sweat_smile I'm assigning you the issue and you can work upon it +1 Make sure to follow the templates provided while making a PR +1

Sure
Thank you

**Comment by codercool3r** [comment]
> > Hey @codercool3r wave, Mentors allotment will take some time sweat_smile I'm assigning you the issue and you can work upon it +1 Make sure to follow the templates provided while making a PR +1
> 
> Sure Thank you



> Hey @codercool3r wave, Mentors allotment will take some time sweat_smile I'm assigning you the issue and you can work upon it +1 Make sure to follow the templates provided while making a PR +1

I am not sure if its an issue at my side, but I am unable to find any HTML or general code file that contains the content in the about page, can you help me out with this? I have checked the files in the repo.

**Comment by varunKT001** [comment]
Hi @codercool3r 👋,
From your query, I'm assuming you are not familiar with ReactJS. In ReactJS, instead of writing plain HTML, CSS, and JavaScript, we use something called components.

Also, I want to say 2 things:

- I guess you didn't read the documentation properly. It clearly mentioned that this project uses ReactJS. Please spend time reading the docs. It'll help you understand the project properly. This is not only for this project, but any project you wish to contribute to. You'll face difficulties if you are unaware of the project's structure.

- I assume you are a beginner at web development. I recommend you choose some other easy and beginner-friendly projects (there are a lot of them), which you can work upon.

Since you were sharp enough to notice the typo, so I'll help you this time 😊
You can find the paragraph in `src/pages/AboutPage/index.js`.

If you are interested in learning more about ReactJS, you can visit [reactjs.org](https://reactjs.org/)
