### ISSUE TITLE
Feature Request: Adding hover effect on home page slides

### ISSUE THREAD

**Issue by PM-00-STAR** [varunKT001/tomper-wear-ecommerce#24]
### Is your feature request related to a problem? Please describe.

Hey, I am a GSSoC22 contributor, would be glad to contribute in your project
It would look more dynamic if you allow me to add hover effect on these 3 slides

![WhatsApp Image 2022-03-04 at 17 59 42](https://user-images.githubusercontent.com/81418245/156763830-81c9854f-fdb5-42ef-a7ec-a1d6bd0f899d.jpg)

### Describe the solution you'd like.

The solution would make them dynamic

**Comment by alceil** [comment]
Can i work on this issue @varunKT001

**Comment by PM-00-STAR** [comment]
> Can i work on this issue @varunKT001

i am working on this

**Comment by varunKT001** [comment]
@PM-00-STAR You are not yet assigned 🙂 so why are you working on it 🙂

**Comment by PM-00-STAR** [comment]
Actually i am interested in frontend issues , if you find relevant issue to this project then please let me know i am willing to contribute in this project

**Comment by varunKT001** [comment]
@PM-00-STAR Sure, whenever I make any frontend-related issue, you can comment on that issue that you're willing to work on it, I'll assign you that. But make sure you comment first because I'll assign on first come first serve basis.

Also if you find some point of improvements, you can create an issue 👍

**Comment by PM-00-STAR** [comment]
Ok
