### ISSUE TITLE
Bug: Shipping Address Page Missing Out Certain Checks

### ISSUE THREAD

**Issue by Shubham29012001** [varunKT001/tomper-wear-ecommerce#30]
### What happened?

While entering the Shipping address, certain checks like Phone Number check (10-12 digit number) and Zip Code should allow only Numeric values are missing out.

![image](https://user-images.githubusercontent.com/59647563/156884452-35049b28-490b-4f8b-b03e-336ed28a220a.png)

### How can we reproduce this bug?

1. Login with the test credentials
2. Add some products to the cart
3. Proceed to the Checkout page
4. Now it will ask you to enter the Shipping address
5. You can write alphabetic, Special-Characters, etc in Zip and Phone number box.

### Additional context (if any)

Can I work on it for GSSoC '22? This issue won't take much time to be solved.

### Urgency (Optional)

Low priority

**Comment by varunKT001** [comment]
Hey @Shubham29012001 👋
There is a check for a phone number. You will get an error pop-up if the phone number you entered doesn't have 10 digits. Also, since it's a number input, no alphabets are allowed in it.

For the zip code, yes, there is no check.

I regex test would fix the issue 👍

Would you like to work upon this now or after completing the other issue you are assigned?

**Comment by Shubham29012001** [comment]
I would like to first work on this issue as I guess it will not take much time and I noticed that in the phone number block, the 'e' character is getting entered while the rest are not.

**Comment by varunKT001** [comment]
Okay 👍
