### ISSUE TITLE
Feature Request:  Image box section as a link

### ISSUE THREAD

**Issue by sourav-912** [varunKT001/tomper-wear-ecommerce#4]
*Not working image box section as a link, I think if it will work, if it will work all over the box section as a link then it would more friendly.

**Comment by varunKT001** [comment]
Hey @sourav-912  👋
Since this project was added, at last, mentors' allotment and other stuff are still pending. Also, I'm yet to create the contribution guidelines and a setup guide.
Don't worry, we'll discuss this issue, once things are on track 👍

PS: 
1. From next on, while creating an issue or pull request, make sure to strictly follow the provided templates. You can leave things blank which are not applicable, but just follow the pattern.
2. Please write a suitable title that describes the issue briefly.

**Comment by sagnik2001** [comment]
Can you assign this issue to me under GSsoc 22

**Comment by sulogna2001** [comment]
Hey Can you assign me this issue under GSSOC22
