### ISSUE TITLE
Removing routes display in about, checkout and products pages.

### ISSUE THREAD

**Issue by Siddhesh777** [varunKT001/tomper-wear-ecommerce#45]
### Describe your issue.

I think there is no need of displaying a current page route in about, products and checkout page.
We have not displayed the route in /orders page and it is looking nice but in case of /about, /products and /checkout pages, we are displaying the route in too much big font which is grabbing attention of user.
Instead we can give some background colour to our Navbar. It will look nice.

### Screenshots (if applicable).

![1](https://user-images.githubusercontent.com/77476772/158997650-b52c701f-4aac-413c-985d-46a039b03969.png)
![2](https://user-images.githubusercontent.com/77476772/158997682-7b6eca75-ec22-4897-8252-e59023e21cdb.png)

### Additional context (if any)

I am contributor at gssoc'22
Please assign this task to me.

**Comment by varunKT001** [comment]
@Siddhesh777 
You don't have any orders, that's why Breadcrumbs are not shown. Order something and then go to the orders page, you'll see the breadcrumbs 😅 
Also, the change you are asking for would be a very breaking change. Also, as I can visualize, I won't look good actually, because of the way the app is constructed 😅 
I'm sorry, I don't think this would work,  😕
